// Generated by CoffeeScript 1.7.1
(function() {
  var Crawler, crawler, fs, processPage;

  Crawler = require("./crawler");

  fs = require('fs');

  processPage = function(error, result, $) {
    var birth, death, lifedates, occupation, p, record, _ref;
    record = {};
    try {
      if (error !== null) {
        console.log("" + (new Date()) + ": " + error.message);
        return null;
      }
      record.uri = "http://dasjuedischehamburg.de" + result.req.path;
      record.title = $("h1.title").text();
      record.abstract = "";
      p = $("div.content p").first();
      record.abstract = p.text().trim();
      if (record.abstract.length > 0 && !record.abstract.endsWith(".")) {
        record.abstract += ". ";
      }
      lifedates = record.abstract;
      record.isPerson = lifedates.match(/\d{4}.+\d{4}/) !== null;
      p = p.next("p");
      record.abstract += p.text().trim();
      p = p.next("p");
      record.abstract += p.first().text().trim();
      record.abstract = record.abstract.split("→").join("");
      record.abstract = record.abstract.truncate(100);
      lifedates = lifedates.match(/(.*)geb\. (.*), gest\. (.*?)\. /);
      if (lifedates !== null) {
        occupation = lifedates[1].trim();
        record.occupation = occupation.replace(/,\s*$/g, '');
        birth = lifedates[2].match(/(.*[0-9].)(\D*)/);
        if (birth !== null) {
          record.birthDate = birth[1].trim();
          record.birthLocation = birth[2].trim();
        }
        death = lifedates[3].match(/(.*[0-9].)(\D*)/);
        if (death !== null) {
          record.deathDate = death[1].trim();
          record.deathLocation = death[2].trim();
        }
      }
      record.author = $("div.content div.field-field-name div.field-items div.field-item").first().text().trim();
      record.images = [];
      $("img.image").each(function(index, img) {
        var image;
        image = {};
        image.thumbUrl = "" + ($(img).attr("src"));
        image.imgDesc = $(img).attr("alt").trim();
        return record.images.push(image);
      });
      record.links = [];
      $("div.content p.text a[href*='/inhalt/']").each(function(index, a) {
        var link;
        link = {};
        link.href = $(a).attr("href").replace(/.*\/inhalt\//, "http://dasjuedischehamburg.de/inhalt/");
        link.text = $(a).text().trim();
        if (link.text.length > 0) {
          record.links.push(link);
        }
        return crawler.checkForQueue(link.href);
      });
      record.glossary = [];
      $(".term").each(function(index, span) {
        var term;
        term = $(span).text().trim();
        if (term.length > 0) {
          return record.glossary.push(term);
        }
      });
      record.next = (_ref = $("a.page-next")) != null ? _ref.attr("href") : void 0;
      if (record.next !== void 0) {
        record.next = "http://dasjuedischehamburg.de" + record.next;
        crawler.checkForQueue(record.next);
      }
      if (record.uri.match(/^.*\/[a-z]$/)) {
        return null;
      } else {
        return record;
      }
    } catch (_error) {
      error = _error;
      fs.appendFile("error.txt", "" + (new Date()) + " Error (" + record.uri + "): " + error.message + " Stack: " + error.stack + "\n");
      return null;
    }
  };

  crawler = new Crawler(processPage, "djh.json");

  crawler.restart("http://dasjuedischehamburg.de/inhalt/a");

}).call(this);
