// Generated by CoffeeScript 1.7.1
(function() {
  var Crawler, crawler, fs, lowerCase, processRujenPage;

  fs = require('fs');

  Crawler = require("./crawler");

  lowerCase = function(url) {
    return encodeURI(decodeURI(url).toLowerCase());
  };

  processRujenPage = function(error, result, $) {
    var record;
    record = {};
    try {
      if (error !== null) {
        console.log("" + (new Date()) + ": " + error.message);
        crawler.checkForQueue(error.url);
        return null;
      }
      if (result.url.indexOf("AllPages") !== -1) {
        console.log("Processing Index Page: " + result.url);
        $("td a").each(function(index, a) {
          var page;
          page = "http://rujen.ru" + ($(a).attr("href"));
          page = lowerCase(page);
          return crawler.checkForQueue(lowerCase(page));
        });
        $("#bodyContent p a").last().each(function(index, a) {
          console.log("Next index page: " + ("http://rujen.ru" + ($(a).attr("href"))));
          return crawler.checkForQueue("http://rujen.ru" + ($(a).attr("href")));
        });
        return null;
      }
      record.uri = lowerCase(result.url);
      try {
        record.id = /var wgArticleId = "?([0-9]+)"?;/g.exec($("head").html())[1];
      } catch (_error) {
        error = _error;
        console.log("Error getting ID (" + record.uri + "): " + error.message);
        fs.appendFile("error.txt", "" + (new Date()) + " Error getting ID (" + record.uri + "): " + error.message + "\n");
        return null;
      }
      record.title = $("h1.firstHeading").text();
      if (record.id === "0") {
        record.empty = "true";
        return record;
      }
      if (record.id === "1") {
        return null;
      }
      record.abstract = $("#bodyContent>p").text().replace("\\n", "").trim();
      record.links = [];
      $("#bodyContent>p>a").each(function(index, a) {
        var h, link;
        link = {};
        h = "http://rujen.ru" + ($(a).attr("href").replace("&action=edit&redlink=1", "").replace("?title=", "/"));
        link.href = lowerCase(h);
        link.text = $(a).text().trim();
        if (link.text.length > 0) {
          record.links.push(link);
        }
        return crawler.checkForQueue(link.href);
      });
      record.categories = [];
      $("#catlinks span a").each(function(index, a) {
        return record.categories.push($(a).text().trim());
      });
      return record;
    } catch (_error) {
      error = _error;
      fs.appendFile("error.txt", "" + (new Date()) + " Error (" + record.uri + "): " + error.message + "\n");
      return null;
    }
  };

  crawler = new Crawler(processRujenPage);

  crawler.restart("http://rujen.ru/index.php/%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:AllPages/%D0%90%D0%91%D0%90%D0%97%D0%9E%D0%92%D0%9A%D0%90");

}).call(this);
